ALTER TABLE TBL_USER MODIFY COLUMN PASSWORD VARCHAR(20);
ALTER TABLE TBL_USER MODIFY COLUMN FIRST_NAME VARCHAR(30);
ALTER TABLE TBL_USER MODIFY COLUMN PHONE VARCHAR(20);
ALTER TABLE TBL_USER MODIFY COLUMN IMG_URL VARCHAR(1024);
