DROP TABLE  IF EXISTS `fundzforus`.`TBL_USER_MESSAGES`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_PROGRAM_BOOKINGS`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_PROGRAM`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_USER_VIDEO_COMMENT`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_USER_VIDEO`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_NEWS_READER`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_USER`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_ROLE`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_PARTNER_IMG`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_PARTNER_VIDEO`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_PARTNER`;
DROP TABLE  IF EXISTS `fundzforus`.`TBL_TENANT`;


SET time_zone='+00:00';

CREATE TABLE `fundzforus`.`TBL_TENANT` (
  `TENANT_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `TENANT_NAME` VARCHAR(100) NOT NULL,
  `TENANT_URL` VARCHAR(1024) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL,
  `EMAIL_ADDRESS` VARCHAR(30) NOT NULL,
  `ADDRESS_LINE1` VARCHAR(100) NOT NULL,
  `ADDRESS_LINE2` VARCHAR(100),
  `CITY` VARCHAR(100),
  `STATE` VARCHAR(100),
  `ZIP_CODE` VARCHAR(100),
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP'
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_ROLE` (
  `ROLE_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ROLE_NAME` VARCHAR(20) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NOT NULL,  
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  CONSTRAINT UC_ROLE1 UNIQUE (ROLE_NAME)
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_USER` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PASSWORD` VARCHAR(20),
  `OLD_PASSWORD` VARCHAR(20),
  `FACEBOOK_ID` VARCHAR(20),
  `GOOGLE_ID` VARCHAR(20),
  `LAST_WRONG_PASSWORD_ATTEMPTS` INTEGER,
  `LAST_LOGIN_DATETIME` TIMESTAMP,
  `ACTIVE_PERIOD` INTEGER,
  `ROLE_ID` INTEGER,
  `TENANT_ID` INTEGER,
  `FIRST_NAME` VARCHAR(30),
  `LAST_NAME` VARCHAR(30) NOT NULL,
  `PHONE` VARCHAR(20),
  `EMAIL` VARCHAR(30) NOT NULL,
  `LOCATION` VARCHAR(30) NOT NULL,
  `IMG_URL` VARCHAR(1024),
  `RECEIVE_NOTIFICATION` VARCHAR(5) NOT NULL,
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  FOREIGN KEY (`ROLE_ID`) REFERENCES TBL_ROLE(`ROLE_ID`),
  FOREIGN KEY (`TENANT_ID`) REFERENCES TBL_TENANT(`TENANT_ID`),
  CONSTRAINT UC_USER1 UNIQUE (EMAIL),
  CONSTRAINT UC_USER2 UNIQUE (FACEBOOK_ID),
  CONSTRAINT UC_USER3 UNIQUE (GOOGLE_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_PARTNER` (
  `PARTNER_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PARTNER_NAME` VARCHAR(200) NOT NULL,
  `DESCRIPTION` VARCHAR(1000) NOT NULL,
  `LOGO_URL` VARCHAR(1024) NOT NULL,
  `CONTACT_NAME` VARCHAR(200)  NOT NULL,
  `CONTACT_PHONE` VARCHAR(200)  NOT NULL,
  `CONTACT_EMAIL` VARCHAR(200)  NOT NULL,
  `CONTACT_ADDRESS` VARCHAR(200)  NOT NULL,
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  CONSTRAINT UC_PARTNER1 UNIQUE (PARTNER_NAME)
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_PARTNER_IMG` (
  `IMG_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IMG_NAME` VARCHAR(200) NOT NULL,
  `IMG_DESCRIPTION` VARCHAR(1000) NOT NULL,
  `IMG_URL` VARCHAR(1024) NOT NULL,
  `PARTNER_ID` INTEGER  NOT NULL,
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  FOREIGN KEY (`PARTNER_ID`) REFERENCES TBL_PARTNER(`PARTNER_ID`),
  CONSTRAINT UC_PARTNER_IMG1 UNIQUE (IMG_NAME, PARTNER_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_PARTNER_VIDEO` (
  `VIDEO_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `VIDEO_NAME` VARCHAR(200) NOT NULL,
  `VIDEO_DESCRIPTION` VARCHAR(1000) NOT NULL,
  `VIDEO_URL` VARCHAR(1024) NOT NULL,
  `PARTNER_ID` INTEGER  NOT NULL,
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  FOREIGN KEY (`PARTNER_ID`) REFERENCES TBL_PARTNER(`PARTNER_ID`),
  CONSTRAINT UC_PARTNER_VIDEO1 UNIQUE (VIDEO_NAME, PARTNER_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_USER_MESSAGES` (
  `MESSAGE_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `MESSAGE_TITLE` VARCHAR(100) NOT NULL,
  `MESSAGE_DESCRIPTION` VARCHAR(2000) NOT NULL,
  `MESSAGE_DATETIME` TIMESTAMP NOT NULL,
  `TENANT_ID` INTEGER NOT NULL,
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  CONSTRAINT UC_USER_MESSAGE_BOARD1 UNIQUE (MESSAGE_TITLE, TENANT_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_PROGRAM` (
  `PROGRAM_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PROGRAM_NAME` VARCHAR(200) NOT NULL,
  `PROGRAM_DESCRIPTION` VARCHAR(2000) NOT NULL,
  `PROGRAM_DETAILS` VARCHAR(4000),
  `PROGRAM_DATETIME` TIMESTAMP NOT NULL,
  `PROGRAM_IMG_URL` VARCHAR(1024) NOT NULL,
  `PROGRAM_VIDEO_URL` VARCHAR(1024) NOT NULL,
  `PROGRAM_ADDRESS` VARCHAR(200) NOT NULL,
  `TENANT_ID` INTEGER NOT NULL,
  `BOOKINGS` INTEGER,
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  CONSTRAINT UC_PROGRAM1 UNIQUE (PROGRAM_NAME, TENANT_ID)
) DEFAULT CHARSET=utf8;


CREATE TABLE `fundzforus`.`TBL_PROGRAM_BOOKINGS` (
  `BOOKING_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PROGRAM_ID` INTEGER NOT NULL,
  `USER_ID` INTEGER NOT NULL,
  `NUMBER_OF_PERSONS` INTEGER NOT NULL,
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  CONSTRAINT UC_PROGRAM_USER1 UNIQUE (PROGRAM_ID, USER_ID),
  FOREIGN KEY (`USER_ID`) REFERENCES TBL_USER(`ID`),
  FOREIGN KEY (`PROGRAM_ID`) REFERENCES TBL_PROGRAM(`PROGRAM_ID`)
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_NEWS_READER` (
  `NEWS_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NEWS_CATEGORY` VARCHAR(200) NOT NULL,
  `NEWS_TITLE` VARCHAR(200) NOT NULL,
  `NEWS_DESCRIPTION` VARCHAR(300),
  `NEWS_IMG_URL` VARCHAR(1024) ,
  `NEWS_PDF_URL` VARCHAR(1024),
  `NEWS_VIDEO_URL` VARCHAR(1024),
  `PUBLISHED_BY` VARCHAR(20),
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NULL,
  `UPDATED_BY` VARCHAR(20)  NULL DEFAULT 'MOBILE_APP',
  CONSTRAINT UC_NEWS_READER1 UNIQUE (NEWS_TITLE)
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_USER_VIDEO` (
  `VIDEO_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `VIDEO_NAME` VARCHAR(200) NOT NULL,
  `VIDEO_DESCRIPTION` VARCHAR(1000) NOT NULL,
  `VIDEO_URL` VARCHAR(1024) NOT NULL,
  `TENANT_ID` INTEGER  NOT NULL,
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  CONSTRAINT UC_USER_VIDEO1 UNIQUE (VIDEO_NAME, TENANT_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE `fundzforus`.`TBL_USER_VIDEO_COMMENT` (
  `USER_VIDEO_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `VIDEO_COMMENT` VARCHAR(1000) NOT NULL,
  `VIDEO_ID` INTEGER  NOT NULL,
  `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  `UPDATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(20) NOT NULL DEFAULT 'MOBILE_APP',
  FOREIGN KEY (`VIDEO_ID`) REFERENCES TBL_USER_VIDEO(`VIDEO_ID`)
) DEFAULT CHARSET=utf8;

INSERT INTO `TBL_ROLE` (`ROLE_NAME`, `DESCRIPTION`)
VALUES ('SUPER_USER', 'System Owner'),
    ('REGULAR_USER', 'Site Level User'),
    ('PARTNER', 'Admin for Set of Regular Users'),
    ('SITE_LEVEL_ADMIN', 'Admin for Specific Branch');

-- Change Tenant Data Start
INSERT INTO `TBL_TENANT` (`TENANT_NAME`, `TENANT_URL`, `ADDRESS_LINE1`, `CITY`, `STATE`, `ZIP_CODE`, `PHONE`, `EMAIL_ADDRESS`)
VALUES ('Rev. Lawrence L. Young', 'cascadeumc.org', '3144 Cascade Rd SW', 'ATLANTA', 'GA', '30311', '(404) 691-5770', 'guest1@fundzforus.org'),
    ('Jeff Struecker', 'calvaryga.com', '7556 Old Moon Rd', 'Columbus', 'TX', '31909', '(706) 322-1491', 'guest2@fundzforus.org'),
    ('Jeff Struecker', 'htelcm.org', '2922 Sandy Plains Rd', 'Marietta', 'GA', '30066', '(770) 971-4600', 'guest3@fundzforus.org');
-- Change Tenant Data End

INSERT INTO `TBL_USER` (`PASSWORD`, `FIRST_NAME`, `LAST_NAME`, `PHONE`, `EMAIL`, `ROLE_ID`, `TENANT_ID`, `LOCATION`, `RECEIVE_NOTIFICATION`, `IMG_URL`)
VALUES ('SITE_ADMIN_1', 'JACK1', 'TEST1', '1211232', 'ADAF1@TEST.COM', 4, 1, 'Dallas, TX', 'true', '/img/user-pic.png'),
    ('SITE_ADMIN_2', 'JACK2', 'TEST2', '1211232', 'ADAF2@TEST.COM', 4, 1, 'Atlanta, GA', 'false', '/img/user-pic.png'),
    ('REG_USER_1', 'JACK3', 'TEST3', '1211232', 'ADAF3@TEST.COM', 2, 1, 'Atlanta, GA', 'true', '/img/user-pic.png'),
    ('REG_USER_2', 'JACK4', 'TEST4', '1211232', 'ADAF4@TEST.COM', 2, 2, 'Dallas, TX', 'false', '/img/user-pic.png'),
    ('PARTNER_1', 'JACK5', 'TEST5', '1211232', 'ADAF5@TEST.COM', 3, 1, 'Atlanta, GA', 'true', '/img/user-pic.png'),
    ('PARTNER_2', 'JACK6', 'TEST6', '1211232', 'ADAF6@TEST.COM', 3, 1, 'Dallas, TX', 'false', '/img/user-pic.png'),
    ('SUP_USER_1', 'COW', 'IT', '23', 'COW@TEST.COM', 1, null, 'Dallas, TX', 'false', '/img/user-pic.png');

INSERT INTO `TBL_PARTNER` (`PARTNER_NAME`, `DESCRIPTION`, `LOGO_URL`, `CONTACT_NAME`, `CONTACT_PHONE`, `CONTACT_EMAIL`, `CONTACT_ADDRESS`)
VALUES ('SIMAVI', 'Simavi, A Healthy Life For All', '/img/partner-1.png', 'Simavi Contact Name', 'Simavi Contact Phone', 'Simavi Contact Email', 'Simavi Contact Address'),
    ('THE POPULATION OF INDIA', 'THE POPULATION OF INDIA', '/img/partner-2.png', 'THE POPULATION OF INDIA Contact Name', 'THE POPULATION OF INDIA Contact Phone', 'THE POPULATION OF INDIA Contact Email', 'THE POPULATION OF INDIA Contact Address'),
    ('BLACK DIAMONDS SUPPORT FOUNDATION', 'BLACK DIAMONDS SUPPORT FOUNDATION NGO', '/img/partner-3.png', 'BLACK DIAMONDS SUPPORT FOUNDATION Contact Name', 'BLACK DIAMONDS SUPPORT FOUNDATION Contact Phone', 'BLACK DIAMONDS SUPPORT FOUNDATION Contact Email', 'BLACK DIAMONDS SUPPORT FOUNDATION Contact Address'),
    ('DANDU FOUNDATION', 'DANDU FOUNDATION NGO', '/img/partner-4.png', 'DANDU FOUNDATION Contact Name', 'DANDU FOUNDATION Contact Phone', 'DANDU FOUNDATION Contact Email', 'DANDU FOUNDATION Contact Address'),
    ('THE FOUNDATION FOR', 'THE FOUNDATION FOR NGO', '/img/partner-5.png', 'THE FOUNDATION FOR Contact Name', 'THE FOUNDATION FOR Contact Phone', 'THE FOUNDATION FOR Contact Email', 'THE FOUNDATION FOR Contact Address'),
    ('THE LITTLE NGO', 'THE LITTLE NGO', '/img/partner-6.png', 'THE LITTLE NGO Contact Name', 'THE LITTLE NGO Contact Phone', 'THE LITTLE NGO Contact Email', 'THE LITTLE NGO Contact Address'),
    ('THE CHALLENGING ONES', 'THE CHALLENGING ONES', '/img/partner-7.png', 'THE CHALLENGING ONES Contact Name', 'THE CHALLENGING ONES Contact Phone', 'THE CHALLENGING ONES Contact Email', 'THE CHALLENGING ONES Contact Address'),
    ('CHILDHOOD TO LIVELIHOOD', 'CHILDHOOD TO LIVELIHOOD NGO', '/img/partner-8.png', 'CHILDHOOD TO LIVELIHOOD Contact Name', 'CHILDHOOD TO LIVELIHOOD Contact Phone', 'CHILDHOOD TO LIVELIHOOD Contact Email', 'CHILDHOOD TO LIVELIHOOD Contact Address'),
    ('NGO BEST PRACTICES', 'NGO BEST PRACTICES', '/img/partner-9.png', 'NGO BEST PRACTICES Contact Name', 'NGO BEST PRACTICES Contact Phone', 'NGO BEST PRACTICES Contact Email', 'NGO BEST PRACTICES Contact Address'),
    ('CANONISATION OF MOTHER THERESA', 'CANONISATION OF MOTHER THERESA', '/img/partner-10.png', 'CANONISATION OF MOTHER THERESA Contact Name', 'CANONISATION OF MOTHER THERESA Contact Phone', 'CANONISATION OF MOTHER THERESA Contact Email', 'CANONISATION OF MOTHER THERESA Contact Address');

INSERT INTO `TBL_PARTNER_IMG` (`IMG_NAME`, `IMG_DESCRIPTION`, `IMG_URL`, `PARTNER_ID`)
VALUES ('BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 1', 'BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 1', '/img/breaking-news2.png', 3),
('BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 2', 'BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 2', '/img/breaking-news3.png', 3),
('BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 3', 'BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 3', '/img/breaking-news4.png', 3),
('BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 4', 'BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 4', '/img/breaking-news5.png', 3),
('BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 7', 'BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 7', '/img/breaking-news7.png', 3),
('BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 8', 'BLACK DIAMONDS SUPPORT FOUNDATION IMG NAME 8', '/img/breaking-news8.png', 3);

INSERT INTO `TBL_PARTNER_VIDEO` (`VIDEO_NAME`, `VIDEO_DESCRIPTION`, `VIDEO_URL`, `PARTNER_ID`)
VALUES ('BLACK DIAMONDS SUPPORT FOUNDATION', 'BLACK DIAMONDS SUPPORT FOUNDATION', '/img/banner-img-2.png', 3);

INSERT INTO `TBL_USER_MESSAGEs` (`MESSAGE_TITLE`, `MESSAGE_DESCRIPTION`, `TENANT_ID`, `MESSAGE_DATETIME`)
VALUES ('Message1', '1. Sed a magna semper, porta purus eu, ullamcorper ligula. Nam sit amet consectetur sapien. Etiam dui ipsum, viverra vel turpis ut, dignissim elementum mauris. Sed dapibus auctor scelerisque.', 1, CURRENT_TIMESTAMP()),
('Message2', '2. Sed a magna semper, porta purus eu, ullamcorper ligula. Nam sit amet consectetur sapien. Etiam dui ipsum, viverra vel turpis ut, dignissim elementum mauris. Sed dapibus auctor scelerisque.', 1, CURRENT_TIMESTAMP()),
('Message3', '3. Sed a magna semper, porta purus eu, ullamcorper ligula. Nam sit amet consectetur sapien. Etiam dui ipsum, viverra vel turpis ut, dignissim elementum mauris. Sed dapibus auctor scelerisque.', 1, CURRENT_TIMESTAMP());

INSERT INTO `TBL_PROGRAM` (`PROGRAM_NAME`, `PROGRAM_DESCRIPTION`, `PROGRAM_DATETIME`, `PROGRAM_IMG_URL`, `PROGRAM_VIDEO_URL`, `PROGRAM_ADDRESS`, `TENANT_ID`)
VALUES ('PROGRAM_NAME1', 'PROGRAM_DESCRIPTION1', CURRENT_TIMESTAMP(), '/img/banner-img-1.png', '/img/banner-img-1.png', '716 Canal St', 1),
('PROGRAM_NAME2', 'PROGRAM_DESCRIPTION2', CURRENT_TIMESTAMP(), '/img/banner-img-2.png', '/img/banner-img-2.png', '717 Canal St', 1),
('PROGRAM_NAME3', 'PROGRAM_DESCRIPTION3', CURRENT_TIMESTAMP(), '/img/banner-img-3.png', '/img/banner-img-3.png', '718 Canal St', 1);

INSERT INTO `TBL_NEWS_READER` (`NEWS_CATEGORY`, `NEWS_TITLE`, `NEWS_DESCRIPTION`, `NEWS_IMG_URL`, `PUBLISHED_BY`)
VALUES ('MARKETING', 'MARKETING TITLE1', 'MARKETING DESCRIPTION1', '/img/news-img-2.png', '3'),
('MARKETING', 'MARKETING TITLE2', 'MARKETING DESCRIPTION2', '/img/news-img-2.png', '3'),
('BEAUTY', 'BEAUTY TITLE1', 'BEAUTY DESCRIPTION1', '/img/news-img-2.png', '3');

INSERT INTO `TBL_USER_VIDEO` (`VIDEO_NAME`, `VIDEO_DESCRIPTION`, `VIDEO_URL`, `TENANT_ID`)
VALUES ('VIDEO_NAME1', 'VIDEO_NAME DESCIPTION1', '/img/banner-img-2.png', 3);